Add test for the GetGroupTasksListForEachUser handler
paypay3/kakeibo-app-api pull request #56
Opened 2020-09-05 09:36 UTC by paypay3

GetGroupTasksListForEachUser handlerのテストを実装しました。

2020-09-05 11:31 UTC, paypay3 commented
1ec799c
PostGroupTasksUser handlerのテストを実装しました。

2020-09-05 13:35 UTC, paypay3 commented
67e532b
GetGroupTasksList handlerのテストを実装しました。

2020-09-05 13:47 UTC, paypay3 commented
5d57319
PostGroupTask handlerのテストを実装しました。

2020-09-05 14:26 UTC, paypay3 commented
eb9ab60
PutGroupTask handlerのテストを実装しました。

2020-09-05 14:36 UTC, paypay3 commented
1b01101
DeleteGroupTask handlerのテストを実装しました。

2020-09-05 17:31 UTC, paypay3 commented
e8e96af
GetGroupTasksListForEachUser handlerのテストを修正しました。

2020-09-05 21:55 UTC, d-kuro requested changes

2020-09-05 21:55 UTC, d-kuro commented on todo-rest-service/handler/group_task_test.go
> +var count int
global 変数のカウントは用途としては良くないと思います
これでカウント実現したい場合は Lock を取らないとダメですね
もっとスコープが限定されてるカウンタにするのが望ましいです

2020-09-05 22:02 UTC, d-kuro commented on todo-rest-service/handler/group_task_test.go
> +var count int
https://qiita.com/yuya_takeyama/items/98e5a9fe6786df11c8a7

2020-09-06 07:43 UTC, paypay3 commented
23ee306
TestDBHandler_GetGroupTasksListForEachUserのresponse.json.goldenを変更しました。

2020-09-06 14:38 UTC, paypay3 commented
d1ec048
現在時刻をテストでMock化できるようTimeManager interfaceを定義しました。

2020-09-07 14:47 UTC, d-kuro approved these changes
count 以外は LGTM です！

2020-09-07 15:38 UTC, paypay3 commented
確認ありがとうございます！

2020-09-07 16:27 UTC, merged